
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoAeonFlux
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label lbltitulo;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.HSeparator hseparator2;
		
		private global::Gtk.Label lblactualizacion;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.HSeparator hseparator3;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Button btnclientes;
		
		private global::Gtk.Button btndepartamentos;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.HSeparator hseparator6;
		
		private global::Gtk.Button btnarticulos;
		
		private global::Gtk.HSeparator hseparator5;
		
		private global::Gtk.HSeparator hseparator4;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Label lblfecha;
		
		private global::Gtk.Label lblhora;
		
		private global::Gtk.VSeparator vseparator1;
		
		private global::Gtk.Button btnsalir;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ProyectoAeonFlux.MainWindow
			this.Name = "ProyectoAeonFlux.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ProyectoAeonFlux.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lbltitulo = new global::Gtk.Label ();
			this.lbltitulo.Name = "lbltitulo";
			this.lbltitulo.LabelProp = global::Mono.Unix.Catalog.GetString ("Aeon Flux");
			this.vbox2.Add (this.lbltitulo);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lbltitulo]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.hbox1.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hseparator2]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblactualizacion = new global::Gtk.Label ();
			this.lblactualizacion.Name = "lblactualizacion";
			this.lblactualizacion.LabelProp = global::Mono.Unix.Catalog.GetString ("Proceso de actualización");
			this.hbox1.Add (this.lblactualizacion);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblactualizacion]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.hbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hseparator1]));
			w4.Position = 2;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.vbox2.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator3]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnclientes = new global::Gtk.Button ();
			this.btnclientes.CanFocus = true;
			this.btnclientes.Name = "btnclientes";
			this.btnclientes.UseUnderline = true;
			this.btnclientes.Label = global::Mono.Unix.Catalog.GetString ("Clientes");
			this.hbox2.Add (this.btnclientes);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnclientes]));
			w8.Position = 0;
			w8.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btndepartamentos = new global::Gtk.Button ();
			this.btndepartamentos.CanFocus = true;
			this.btndepartamentos.Name = "btndepartamentos";
			this.btndepartamentos.UseUnderline = true;
			this.btndepartamentos.Label = global::Mono.Unix.Catalog.GetString ("Departamentos");
			this.hbox2.Add (this.btndepartamentos);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btndepartamentos]));
			w9.Position = 1;
			w9.Fill = false;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hseparator6 = new global::Gtk.HSeparator ();
			this.hseparator6.Name = "hseparator6";
			this.hbox5.Add (this.hseparator6);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.hseparator6]));
			w11.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.btnarticulos = new global::Gtk.Button ();
			this.btnarticulos.CanFocus = true;
			this.btnarticulos.Name = "btnarticulos";
			this.btnarticulos.UseUnderline = true;
			this.btnarticulos.Label = global::Mono.Unix.Catalog.GetString ("Articulos");
			this.hbox5.Add (this.btnarticulos);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.btnarticulos]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hseparator5 = new global::Gtk.HSeparator ();
			this.hseparator5.Name = "hseparator5";
			this.hbox5.Add (this.hseparator5);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.hseparator5]));
			w13.Position = 2;
			this.hbox4.Add (this.hbox5);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.hbox5]));
			w14.Position = 0;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator4 = new global::Gtk.HSeparator ();
			this.hseparator4.Name = "hseparator4";
			this.vbox3.Add (this.hseparator4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator4]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			this.vbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox3]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblfecha = new global::Gtk.Label ();
			this.lblfecha.Name = "lblfecha";
			this.vbox4.Add (this.lblfecha);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblfecha]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblhora = new global::Gtk.Label ();
			this.lblhora.Name = "lblhora";
			this.vbox4.Add (this.lblhora);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblhora]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.hbox3.Add (this.vbox4);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox4]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hbox3.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vseparator1]));
			w21.Position = 1;
			w21.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnsalir = new global::Gtk.Button ();
			this.btnsalir.CanFocus = true;
			this.btnsalir.Name = "btnsalir";
			this.btnsalir.UseUnderline = true;
			this.btnsalir.Label = global::Mono.Unix.Catalog.GetString ("Salir");
			this.hbox3.Add (this.btnsalir);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnsalir]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 342;
			this.DefaultHeight = 217;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.btnclientes.Clicked += new global::System.EventHandler (this.OnBtnclientesClicked);
			this.btndepartamentos.Clicked += new global::System.EventHandler (this.OnBtndepartamentosClicked);
			this.btnarticulos.Clicked += new global::System.EventHandler (this.OnBtnarticulosClicked);
			this.btnsalir.Clicked += new global::System.EventHandler (this.OnBtnsalirClicked);
		}
	}
}
