
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoAeonFlux
{
	public partial class Validaciones
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ProyectoAeonFlux.Validaciones
			this.Name = "ProyectoAeonFlux.Validaciones";
			this.Title = global::Mono.Unix.Catalog.GetString ("Validaciones");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
