
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoAeonFlux
{
	public partial class Departamentos
	{
		private global::Gtk.VBox vbox10;
		
		private global::Gtk.VBox vbox11;
		
		private global::Gtk.HBox hbox16;
		
		private global::Gtk.HSeparator hseparator12;
		
		private global::Gtk.Label lbldepartamentos;
		
		private global::Gtk.HSeparator hseparator11;
		
		private global::Gtk.HBox hbox17;
		
		private global::Gtk.Label lblcod;
		
		private global::Gtk.Entry entcod;
		
		private global::Gtk.HBox hbox18;
		
		private global::Gtk.Label lbldesc;
		
		private global::Gtk.Entry entdesc;
		
		private global::Gtk.VBox vbox12;
		
		private global::Gtk.HBox hbox19;
		
		private global::Gtk.Button btnbuscar;
		
		private global::Gtk.Button btnIncluir;
		
		private global::Gtk.Button btnmodificar;
		
		private global::Gtk.HSeparator hseparator10;
		
		private global::Gtk.HBox hbox20;
		
		private global::Gtk.Button btnreactivar;
		
		private global::Gtk.Button btneliminar;
		
		private global::Gtk.Button btncancelar;
		
		private global::Gtk.HBox hbox15;
		
		private global::Gtk.VBox vbox13;
		
		private global::Gtk.Label lblfecha;
		
		private global::Gtk.Label lblhora;
		
		private global::Gtk.VSeparator vseparator3;
		
		private global::Gtk.Button btnvolver;
		
		private global::Gtk.Button btnsalir;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ProyectoAeonFlux.Departamentos
			this.Name = "ProyectoAeonFlux.Departamentos";
			this.Title = global::Mono.Unix.Catalog.GetString ("Departamentos");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ProyectoAeonFlux.Departamentos.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox ();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.hseparator12 = new global::Gtk.HSeparator ();
			this.hseparator12.Name = "hseparator12";
			this.hbox16.Add (this.hseparator12);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.hseparator12]));
			w1.Position = 0;
			// Container child hbox16.Gtk.Box+BoxChild
			this.lbldepartamentos = new global::Gtk.Label ();
			this.lbldepartamentos.Name = "lbldepartamentos";
			this.lbldepartamentos.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color='blue'>Departamentos</span>");
			this.lbldepartamentos.UseMarkup = true;
			this.hbox16.Add (this.lbldepartamentos);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.lbldepartamentos]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.hseparator11 = new global::Gtk.HSeparator ();
			this.hseparator11.Name = "hseparator11";
			this.hbox16.Add (this.hseparator11);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.hseparator11]));
			w3.Position = 2;
			this.vbox11.Add (this.hbox16);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hbox16]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox17 = new global::Gtk.HBox ();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.lblcod = new global::Gtk.Label ();
			this.lblcod.Name = "lblcod";
			this.lblcod.LabelProp = global::Mono.Unix.Catalog.GetString ("Codigo");
			this.hbox17.Add (this.lblcod);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.lblcod]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.entcod = new global::Gtk.Entry ();
			this.entcod.CanFocus = true;
			this.entcod.Name = "entcod";
			this.entcod.IsEditable = true;
			this.entcod.InvisibleChar = '•';
			this.hbox17.Add (this.entcod);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.entcod]));
			w6.Position = 1;
			w6.Expand = false;
			this.vbox11.Add (this.hbox17);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hbox17]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox18 = new global::Gtk.HBox ();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.lbldesc = new global::Gtk.Label ();
			this.lbldesc.Name = "lbldesc";
			this.lbldesc.LabelProp = global::Mono.Unix.Catalog.GetString ("Descripción");
			this.hbox18.Add (this.lbldesc);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.lbldesc]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.entdesc = new global::Gtk.Entry ();
			this.entdesc.CanFocus = true;
			this.entdesc.Name = "entdesc";
			this.entdesc.IsEditable = true;
			this.entdesc.InvisibleChar = '•';
			this.hbox18.Add (this.entdesc);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.entdesc]));
			w9.Position = 1;
			this.vbox11.Add (this.hbox18);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hbox18]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox10.Add (this.vbox11);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.vbox11]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox ();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.btnbuscar = new global::Gtk.Button ();
			this.btnbuscar.Sensitive = false;
			this.btnbuscar.CanFocus = true;
			this.btnbuscar.Name = "btnbuscar";
			this.btnbuscar.UseUnderline = true;
			this.btnbuscar.Label = global::Mono.Unix.Catalog.GetString ("Buscar");
			this.hbox19.Add (this.btnbuscar);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.btnbuscar]));
			w12.Position = 0;
			w12.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.btnIncluir = new global::Gtk.Button ();
			this.btnIncluir.Sensitive = false;
			this.btnIncluir.CanFocus = true;
			this.btnIncluir.Name = "btnIncluir";
			this.btnIncluir.UseUnderline = true;
			this.btnIncluir.Label = global::Mono.Unix.Catalog.GetString ("Incluir");
			this.hbox19.Add (this.btnIncluir);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.btnIncluir]));
			w13.Position = 1;
			w13.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.btnmodificar = new global::Gtk.Button ();
			this.btnmodificar.Sensitive = false;
			this.btnmodificar.CanFocus = true;
			this.btnmodificar.Name = "btnmodificar";
			this.btnmodificar.UseUnderline = true;
			this.btnmodificar.Label = global::Mono.Unix.Catalog.GetString ("Modificar");
			this.hbox19.Add (this.btnmodificar);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.btnmodificar]));
			w14.Position = 2;
			w14.Fill = false;
			this.vbox12.Add (this.hbox19);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox19]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hseparator10 = new global::Gtk.HSeparator ();
			this.hseparator10.Name = "hseparator10";
			this.vbox12.Add (this.hseparator10);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hseparator10]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox20 = new global::Gtk.HBox ();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.btnreactivar = new global::Gtk.Button ();
			this.btnreactivar.Sensitive = false;
			this.btnreactivar.CanFocus = true;
			this.btnreactivar.Name = "btnreactivar";
			this.btnreactivar.UseUnderline = true;
			this.btnreactivar.Label = global::Mono.Unix.Catalog.GetString ("Reactivar");
			this.hbox20.Add (this.btnreactivar);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.btnreactivar]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.btneliminar = new global::Gtk.Button ();
			this.btneliminar.Sensitive = false;
			this.btneliminar.CanFocus = true;
			this.btneliminar.Name = "btneliminar";
			this.btneliminar.UseUnderline = true;
			this.btneliminar.Label = global::Mono.Unix.Catalog.GetString ("Eliminar");
			this.hbox20.Add (this.btneliminar);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.btneliminar]));
			w18.Position = 1;
			w18.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.btncancelar = new global::Gtk.Button ();
			this.btncancelar.Sensitive = false;
			this.btncancelar.CanFocus = true;
			this.btncancelar.Name = "btncancelar";
			this.btncancelar.UseUnderline = true;
			this.btncancelar.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.hbox20.Add (this.btncancelar);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.btncancelar]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox12.Add (this.hbox20);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox20]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			this.vbox10.Add (this.vbox12);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.vbox12]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox ();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox ();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.lblfecha = new global::Gtk.Label ();
			this.lblfecha.Name = "lblfecha";
			this.vbox13.Add (this.lblfecha);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.lblfecha]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.lblhora = new global::Gtk.Label ();
			this.lblhora.Name = "lblhora";
			this.vbox13.Add (this.lblhora);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.lblhora]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			this.hbox15.Add (this.vbox13);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.vbox13]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.vseparator3 = new global::Gtk.VSeparator ();
			this.vseparator3.Name = "vseparator3";
			this.hbox15.Add (this.vseparator3);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.vseparator3]));
			w25.Position = 1;
			w25.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.btnvolver = new global::Gtk.Button ();
			this.btnvolver.CanFocus = true;
			this.btnvolver.Name = "btnvolver";
			this.btnvolver.UseUnderline = true;
			this.btnvolver.Label = global::Mono.Unix.Catalog.GetString ("Volver");
			this.hbox15.Add (this.btnvolver);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.btnvolver]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.btnsalir = new global::Gtk.Button ();
			this.btnsalir.CanFocus = true;
			this.btnsalir.Name = "btnsalir";
			this.btnsalir.UseUnderline = true;
			this.btnsalir.Label = global::Mono.Unix.Catalog.GetString ("Salir");
			this.hbox15.Add (this.btnsalir);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.btnsalir]));
			w27.Position = 3;
			w27.Expand = false;
			this.vbox10.Add (this.hbox15);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox15]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			this.Add (this.vbox10);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 447;
			this.DefaultHeight = 212;
			this.Show ();
			this.entcod.Changed += new global::System.EventHandler (this.OnEntcodChanged);
			this.entdesc.Changed += new global::System.EventHandler (this.OnEntdescChanged);
			this.btnbuscar.Clicked += new global::System.EventHandler (this.OnBtnbuscarClicked);
			this.btnmodificar.Clicked += new global::System.EventHandler (this.OnBtnmodificarClicked);
			this.btnreactivar.Clicked += new global::System.EventHandler (this.OnBtnreactivarClicked);
			this.btneliminar.Clicked += new global::System.EventHandler (this.OnBtneliminarClicked);
			this.btncancelar.Clicked += new global::System.EventHandler (this.OnBtncancelarClicked);
			this.btnvolver.Clicked += new global::System.EventHandler (this.OnBtnvolverClicked);
			this.btnsalir.Clicked += new global::System.EventHandler (this.OnBtnsalirClicked);
		}
	}
}
