
// This file has been generated by the GUI designer. Do not modify.
namespace ProyectoAeonFlux
{
	public partial class Clientes
	{
		private global::Gtk.VBox vbox14;
		
		private global::Gtk.VBox vbox15;
		
		private global::Gtk.HBox hbox21;
		
		private global::Gtk.HSeparator hseparator15;
		
		private global::Gtk.Label lblclientes;
		
		private global::Gtk.HSeparator hseparator14;
		
		private global::Gtk.HBox hbox22;
		
		private global::Gtk.Label lblrif;
		
		private global::Gtk.Entry entrif;
		
		private global::Gtk.Label lblnombre;
		
		private global::Gtk.Entry entnombre;
		
		private global::Gtk.HBox hbox23;
		
		private global::Gtk.Label lbldir;
		
		private global::Gtk.Entry entdir;
		
		private global::Gtk.VBox vbox16;
		
		private global::Gtk.HBox hbox24;
		
		private global::Gtk.Label lbltlfno;
		
		private global::Gtk.Entry enttlfno;
		
		private global::Gtk.HBox hbox25;
		
		private global::Gtk.Button btnbuscar;
		
		private global::Gtk.Button btnincluir;
		
		private global::Gtk.Button btnmodificar;
		
		private global::Gtk.HSeparator hseparator13;
		
		private global::Gtk.HBox hbox26;
		
		private global::Gtk.Button btnreactivar;
		
		private global::Gtk.Button btneliminar;
		
		private global::Gtk.Button btncancelar;
		
		private global::Gtk.HBox hbox27;
		
		private global::Gtk.VBox vbox17;
		
		private global::Gtk.Label lblfecha;
		
		private global::Gtk.Label lblhora;
		
		private global::Gtk.VSeparator vseparator4;
		
		private global::Gtk.Button btnvolver;
		
		private global::Gtk.Button btnsalir;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ProyectoAeonFlux.Clientes
			this.Name = "ProyectoAeonFlux.Clientes";
			this.Title = global::Mono.Unix.Catalog.GetString ("Clientes");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ProyectoAeonFlux.Clientes.Gtk.Container+ContainerChild
			this.vbox14 = new global::Gtk.VBox ();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.vbox15 = new global::Gtk.VBox ();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox21 = new global::Gtk.HBox ();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.hseparator15 = new global::Gtk.HSeparator ();
			this.hseparator15.Name = "hseparator15";
			this.hbox21.Add (this.hseparator15);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.hseparator15]));
			w1.Position = 0;
			// Container child hbox21.Gtk.Box+BoxChild
			this.lblclientes = new global::Gtk.Label ();
			this.lblclientes.Name = "lblclientes";
			this.lblclientes.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color='blue'>Clientes</span>");
			this.lblclientes.UseMarkup = true;
			this.hbox21.Add (this.lblclientes);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.lblclientes]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.hseparator14 = new global::Gtk.HSeparator ();
			this.hseparator14.Name = "hseparator14";
			this.hbox21.Add (this.hseparator14);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.hseparator14]));
			w3.Position = 2;
			this.vbox15.Add (this.hbox21);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.hbox21]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox22 = new global::Gtk.HBox ();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 6;
			// Container child hbox22.Gtk.Box+BoxChild
			this.lblrif = new global::Gtk.Label ();
			this.lblrif.Name = "lblrif";
			this.lblrif.LabelProp = global::Mono.Unix.Catalog.GetString ("RIF");
			this.hbox22.Add (this.lblrif);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.lblrif]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.entrif = new global::Gtk.Entry ();
			this.entrif.CanFocus = true;
			this.entrif.Name = "entrif";
			this.entrif.IsEditable = true;
			this.entrif.InvisibleChar = '•';
			this.hbox22.Add (this.entrif);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.entrif]));
			w6.Position = 1;
			// Container child hbox22.Gtk.Box+BoxChild
			this.lblnombre = new global::Gtk.Label ();
			this.lblnombre.Name = "lblnombre";
			this.lblnombre.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre");
			this.hbox22.Add (this.lblnombre);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.lblnombre]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.entnombre = new global::Gtk.Entry ();
			this.entnombre.CanFocus = true;
			this.entnombre.Name = "entnombre";
			this.entnombre.IsEditable = true;
			this.entnombre.InvisibleChar = '•';
			this.hbox22.Add (this.entnombre);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.entnombre]));
			w8.Position = 3;
			this.vbox15.Add (this.hbox22);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.hbox22]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox23 = new global::Gtk.HBox ();
			this.hbox23.Name = "hbox23";
			this.hbox23.Spacing = 6;
			// Container child hbox23.Gtk.Box+BoxChild
			this.lbldir = new global::Gtk.Label ();
			this.lbldir.Name = "lbldir";
			this.lbldir.LabelProp = global::Mono.Unix.Catalog.GetString ("Direccion");
			this.hbox23.Add (this.lbldir);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox23 [this.lbldir]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.entdir = new global::Gtk.Entry ();
			this.entdir.CanFocus = true;
			this.entdir.Name = "entdir";
			this.entdir.IsEditable = true;
			this.entdir.InvisibleChar = '•';
			this.hbox23.Add (this.entdir);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox23 [this.entdir]));
			w11.Position = 1;
			this.vbox15.Add (this.hbox23);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.hbox23]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox14.Add (this.vbox15);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.vbox15]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.vbox16 = new global::Gtk.VBox ();
			this.vbox16.Name = "vbox16";
			this.vbox16.Spacing = 6;
			// Container child vbox16.Gtk.Box+BoxChild
			this.hbox24 = new global::Gtk.HBox ();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 6;
			// Container child hbox24.Gtk.Box+BoxChild
			this.lbltlfno = new global::Gtk.Label ();
			this.lbltlfno.Name = "lbltlfno";
			this.lbltlfno.LabelProp = global::Mono.Unix.Catalog.GetString ("Telefono");
			this.hbox24.Add (this.lbltlfno);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.lbltlfno]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.enttlfno = new global::Gtk.Entry ();
			this.enttlfno.CanFocus = true;
			this.enttlfno.Name = "enttlfno";
			this.enttlfno.IsEditable = true;
			this.enttlfno.InvisibleChar = '•';
			this.hbox24.Add (this.enttlfno);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.enttlfno]));
			w15.Position = 1;
			w15.Expand = false;
			this.vbox16.Add (this.hbox24);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.hbox24]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.hbox25 = new global::Gtk.HBox ();
			this.hbox25.Name = "hbox25";
			this.hbox25.Spacing = 6;
			// Container child hbox25.Gtk.Box+BoxChild
			this.btnbuscar = new global::Gtk.Button ();
			this.btnbuscar.Sensitive = false;
			this.btnbuscar.CanFocus = true;
			this.btnbuscar.Name = "btnbuscar";
			this.btnbuscar.UseUnderline = true;
			this.btnbuscar.Label = global::Mono.Unix.Catalog.GetString ("Buscar");
			this.hbox25.Add (this.btnbuscar);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.btnbuscar]));
			w17.Position = 0;
			w17.Fill = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.btnincluir = new global::Gtk.Button ();
			this.btnincluir.Sensitive = false;
			this.btnincluir.CanFocus = true;
			this.btnincluir.Name = "btnincluir";
			this.btnincluir.UseUnderline = true;
			this.btnincluir.Label = global::Mono.Unix.Catalog.GetString ("Incluir");
			this.hbox25.Add (this.btnincluir);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.btnincluir]));
			w18.Position = 1;
			w18.Fill = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.btnmodificar = new global::Gtk.Button ();
			this.btnmodificar.Sensitive = false;
			this.btnmodificar.CanFocus = true;
			this.btnmodificar.Name = "btnmodificar";
			this.btnmodificar.UseUnderline = true;
			this.btnmodificar.Label = global::Mono.Unix.Catalog.GetString ("Modificar");
			this.hbox25.Add (this.btnmodificar);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.btnmodificar]));
			w19.Position = 2;
			w19.Fill = false;
			this.vbox16.Add (this.hbox25);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.hbox25]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.hseparator13 = new global::Gtk.HSeparator ();
			this.hseparator13.Name = "hseparator13";
			this.vbox16.Add (this.hseparator13);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.hseparator13]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox14.Add (this.vbox16);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.vbox16]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox26 = new global::Gtk.HBox ();
			this.hbox26.Name = "hbox26";
			this.hbox26.Spacing = 6;
			// Container child hbox26.Gtk.Box+BoxChild
			this.btnreactivar = new global::Gtk.Button ();
			this.btnreactivar.Sensitive = false;
			this.btnreactivar.CanFocus = true;
			this.btnreactivar.Name = "btnreactivar";
			this.btnreactivar.UseUnderline = true;
			this.btnreactivar.Label = global::Mono.Unix.Catalog.GetString ("Reactivar");
			this.hbox26.Add (this.btnreactivar);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox26 [this.btnreactivar]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox26.Gtk.Box+BoxChild
			this.btneliminar = new global::Gtk.Button ();
			this.btneliminar.Sensitive = false;
			this.btneliminar.CanFocus = true;
			this.btneliminar.Name = "btneliminar";
			this.btneliminar.UseUnderline = true;
			this.btneliminar.Label = global::Mono.Unix.Catalog.GetString ("Eliminar");
			this.hbox26.Add (this.btneliminar);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox26 [this.btneliminar]));
			w24.Position = 1;
			w24.Fill = false;
			// Container child hbox26.Gtk.Box+BoxChild
			this.btncancelar = new global::Gtk.Button ();
			this.btncancelar.Sensitive = false;
			this.btncancelar.CanFocus = true;
			this.btncancelar.Name = "btncancelar";
			this.btncancelar.UseUnderline = true;
			this.btncancelar.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.hbox26.Add (this.btncancelar);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox26 [this.btncancelar]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox14.Add (this.hbox26);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox26]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox27 = new global::Gtk.HBox ();
			this.hbox27.Name = "hbox27";
			this.hbox27.Spacing = 6;
			// Container child hbox27.Gtk.Box+BoxChild
			this.vbox17 = new global::Gtk.VBox ();
			this.vbox17.Name = "vbox17";
			this.vbox17.Spacing = 6;
			// Container child vbox17.Gtk.Box+BoxChild
			this.lblfecha = new global::Gtk.Label ();
			this.lblfecha.Name = "lblfecha";
			this.vbox17.Add (this.lblfecha);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.lblfecha]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox17.Gtk.Box+BoxChild
			this.lblhora = new global::Gtk.Label ();
			this.lblhora.Name = "lblhora";
			this.vbox17.Add (this.lblhora);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.lblhora]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			this.hbox27.Add (this.vbox17);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox27 [this.vbox17]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox27.Gtk.Box+BoxChild
			this.vseparator4 = new global::Gtk.VSeparator ();
			this.vseparator4.Name = "vseparator4";
			this.hbox27.Add (this.vseparator4);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox27 [this.vseparator4]));
			w30.Position = 1;
			w30.Fill = false;
			// Container child hbox27.Gtk.Box+BoxChild
			this.btnvolver = new global::Gtk.Button ();
			this.btnvolver.CanFocus = true;
			this.btnvolver.Name = "btnvolver";
			this.btnvolver.UseUnderline = true;
			this.btnvolver.Label = global::Mono.Unix.Catalog.GetString ("Volver");
			this.hbox27.Add (this.btnvolver);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox27 [this.btnvolver]));
			w31.Position = 2;
			w31.Expand = false;
			w31.Fill = false;
			// Container child hbox27.Gtk.Box+BoxChild
			this.btnsalir = new global::Gtk.Button ();
			this.btnsalir.CanFocus = true;
			this.btnsalir.Name = "btnsalir";
			this.btnsalir.UseUnderline = true;
			this.btnsalir.Label = global::Mono.Unix.Catalog.GetString ("Salir");
			this.hbox27.Add (this.btnsalir);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox27 [this.btnsalir]));
			w32.Position = 3;
			w32.Expand = false;
			w32.Fill = false;
			this.vbox14.Add (this.hbox27);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox27]));
			w33.Position = 3;
			w33.Expand = false;
			w33.Fill = false;
			this.Add (this.vbox14);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 505;
			this.DefaultHeight = 256;
			this.Show ();
			this.entrif.Changed += new global::System.EventHandler (this.OnEntrifChanged);
			this.entnombre.Changed += new global::System.EventHandler (this.OnEntnombreChanged);
			this.entdir.Changed += new global::System.EventHandler (this.OnEntdirChanged);
			this.enttlfno.Changed += new global::System.EventHandler (this.OnEnttlfnoChanged);
			this.btnbuscar.Clicked += new global::System.EventHandler (this.OnBtnbuscarClicked);
			this.btnincluir.Clicked += new global::System.EventHandler (this.OnBtnincluirClicked);
			this.btnmodificar.Clicked += new global::System.EventHandler (this.OnBtnmodificarClicked);
			this.btnreactivar.Clicked += new global::System.EventHandler (this.OnBtnreactivarClicked);
			this.btneliminar.Clicked += new global::System.EventHandler (this.OnBtneliminarClicked);
			this.btncancelar.Clicked += new global::System.EventHandler (this.OnBtncancelarClicked);
			this.btnvolver.Clicked += new global::System.EventHandler (this.OnBtnvolverClicked);
			this.btnsalir.Clicked += new global::System.EventHandler (this.OnBtnsalirClicked);
		}
	}
}
